version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - static_volume:/var/www/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./app/db/:/var/lib/postgresql/data
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/www/static
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume:
